---
title: My dynamic report
output: html_fragment
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, error=FALSE)

```

```{css}
body {
  font-family: Arial;
  line-height: 1.5;
  margin: 20px;
}

h2 {
  border-bottom: 2px solid #4a90e2;
  padding-bottom: 4px;
}
```

## Bus Journey Analysis

This report explores data collected from my daily bus journeys. 
This analysis explores whether weather conditions impact travel time.

Using these data in below

## Data
- Weather
- Travel time (minutes)
- crowdedness of the buss
- on-time performance 

```{r}
library(tidyverse)

# reading the csv
logged_data <- read_csv("~/Desktop/stats220/project2/bus_survey.csv")

# Rename variables to cleaner names
latest_data <- logged_data %>%
  rename(
    timestamp = Timestamp,
    score = Score,
    minutes = `How many minutes does  bus journey take to University?`,
    day = `What day was your trip?`,
    weather = `What was the weather during your trip?`,
    on_time = `Was your bus on time?`,
    crowdedness = `How crowded was the bus?`
  )

# Summary values
mean_time <- mean(latest_data$minutes, na.rm = TRUE)
max_time <- max(latest_data$minutes, na.rm = TRUE)


# Bar chart 1: Weather
ggplot(latest_data, aes(x = weather)) +
  geom_bar() +
  labs(title = "Trips by Weather", x = "Weather", y = "Count")


# Bar chart 2: On-time performance
ggplot(latest_data, aes(x = on_time)) + geom_bar() +labs(title = "Bus On-Time Status", x = "On Time?", y = "Count")

# Bar chart 3: Crowdedness
ggplot(latest_data, aes(x = crowdedness)) + geom_bar() + labs(title = "Bus Crowdedness", x = "Crowded Level", y = "Count")


paste("The average travel time is", round(mean_time, 1), "minutes.")
paste("The longest trip recorded was",max_time ,"minutes.")

```

